# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   creationTimestamp: null
#   labels:
#     app: flaskdemo
#   name: flaskdemo
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: flaskdemo
#   strategy: {}
#   template:
#     metadata:
#       creationTimestamp: null
#       labels:
#         app: flaskdemo
#     spec:
#       containers:
#       - image: sikanderali/test:1
#         name: flaskdemo
#         resources: {}
# status: {}
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: lb-service
#   labels:
#     app: lb-service
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 80
#     targetPort: 5000
#   selector:
#     app: flaskdemo
apiVersion: v1
kind: Service
metadata:
  name: flaskdemo-service
  labels:
    app: flaskdemo
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30001 # You can select any available port between 30000-32767
  selector:
    app: flaskdemo
